services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data:/opt/data

    environment:
      - CLUSTER_NAME=steam-cluster
    
    env_file:
      - ./hadoop-tool/hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8

    container_name: datanode1

    volumes:
      - hadoop_datanode1:/hadoop/dfs/data

    environment:
      - SERVICE_PRECONDITION=namenode:9870

    env_file:
      - ./hadoop-tool/hadoop.env

    depends_on:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8

    container_name: datanode2

    volumes:
      - hadoop_datanode2:/hadoop/dfs/data

    environment:
      - SERVICE_PRECONDITION=namenode:9870

    env_file:
      - ./hadoop-tool/hadoop.env
      
    depends_on:
      - namenode

  spark-notebook:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: spark-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=easy_spark
    depends_on:
      - namenode

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    volumes:
      - hive_metastore_postgresql:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-tool/hive.env
    command: /opt/hive/bin/hive --service metastore
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
      - namenode

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./hadoop-tool/hive.env
    ports:
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - hive-metastore
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # 2 listener:
      # PLAINTEXT      → dùng trong Docker network (container gọi nhau)
      # PLAINTEXT_HOST → dùng từ ngoài Docker (Windows host)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hive_metastore_postgresql:
  mongodb_data: