services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data:/opt/data

    environment:
      - CLUSTER_NAME=steam-cluster
    
    env_file:
      - ./hadoop-tool/hadoop.env

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8

    container_name: datanode1

    volumes:
      - hadoop_datanode1:/hadoop/dfs/data

    environment:
      - SERVICE_PRECONDITION=namenode:9870

    env_file:
      - ./hadoop-tool/hadoop.env

    depends_on:
      - namenode

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8

    container_name: datanode2

    volumes:
      - hadoop_datanode2:/hadoop/dfs/data

    environment:
      - SERVICE_PRECONDITION=namenode:9870

    env_file:
      - ./hadoop-tool/hadoop.env
      
    depends_on:
      - namenode

  spark-notebook:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: spark-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_TOKEN=easy_spark
    depends_on:
      - namenode

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    volumes:
      - hive_metastore_postgresql:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-tool/hive.env
    command: /opt/hive/bin/hive --service metastore
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
      - namenode

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./hadoop-tool/hive.env
    ports:
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - hive-metastore


volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hive_metastore_postgresql: